<?php

define("PANEL_UNEXPANDABLE", 0);
define("PANEL_EXPANDABLE_EXPAND", 1);
define("PANEL_EXPANDABLE_NOEXPAND", 2);

define("PAGE_POSITION_NONE", 0);
define("PAGE_POSITION_TOP", 1);
define("PAGE_POSITION_BOTTOM", 2);
define("PAGE_POSITION_BOTH", 3);

?>
